version: "3.9"

x-common-vars:
  - &MINER_SEED 014c7214d881bff4e992ed4f307f52116c327984a9d20e198840ca9058726026
  - &STACKING_CYCLES ${STACKING_CYCLES:-1} # number of cycles to stack-stx or stack-extend for
  - &POX_PREPARE_LENGTH ${POX_PREPARE_LENGTH:-5}
  - &POX_REWARD_LENGTH ${POX_REWARD_LENGTH:-20}
  - &REWARD_RECIPIENT ${REWARD_RECIPIENT:-STQM73RQC4EX0A07KWG1J5ECZJYBZS4SJ4ERC6WN} # priv: 6ad9cadb42d4edbfbe0c5bfb3b8a4125ddced021c4174f829b714ccbf527f02001
  - &EXIT_FROM_MONITOR 1 # set to "1" to automatically shut down via monitor.ts

services:
  bitcoind:
    networks:
      - stacks
    image: dobtc/bitcoin:25.1
    restart: unless-stopped
    ports:
      - "18443:18443"
      - "18444:18444"
    volumes:
      - ./configs/bitcoin.conf:/home/.bitcoin/bitcoin.conf
      - ./chainstate:/chainstate
    environment:
      BITCOIN_DATA: /chainstate/bitcoin-data
    command:
      - -conf=/home/.bitcoin/bitcoin.conf

  stacks-node:
    networks:
      - stacks
    image: blockstack/stacks-core:3.0.0.0.0-rc3
    restart: unless-stopped
    depends_on:
      - bitcoind
    ports:
      - "20443:20443"
    volumes:
      - ./configs/stacks-miner.toml/:/app/config.toml
      - ./chainstate:/chainstate
    # environment:
      # STACKS_LOG_TRACE: 1 # uncomment for trace logging
      # STACKS_LOG_DEBUG: 1
      # RUST_LOG: debug
    command:
      - /bin/stacks-node
      - start
      - --config
      - /app/config.toml

  # stacker:
  #   networks:
  #     - stacks
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.stacker
  #   environment:
  #     STACKS_CORE_RPC_HOST: stacks-node
  #     STACKS_CORE_RPC_PORT: 20443
  #     STACKING_CYCLES: *STACKING_CYCLES
  #     STACKING_KEYS: 6a1a754ba863d7bab14adbbc3f8ebb090af9e871ace621d3e5ab634e1422885e01,b463f0df6c05d2f156393eee73f8016c5372caa0e9e29a901bb7171d90dc4f1401,7036b29cb5e235e5fd9b09ae3e8eec4404e44906814d5d01cbca968a60ed4bfb01
  #     STACKS_25_HEIGHT: *STACKS_25_HEIGHT
  #     STACKS_30_HEIGHT: *STACKS_30_HEIGHT
  #     POX_PREPARE_LENGTH: *POX_PREPARE_LENGTH
  #     POX_REWARD_LENGTH: *POX_REWARD_LENGTH
  #     STACKING_INTERVAL: 2 # interval (seconds) for checking if stacking transactions are needed
  #     POST_TX_WAIT: 10 # seconds to wait after a stacking transaction broadcast before continuing the loop
  #     SERVICE_NAME: stacker
  #   depends_on:
  #     - stacks-node

  # monitor:
  #   networks:
  #     - stacks
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.stacker
  #   environment:
  #     STACKS_CORE_RPC_HOST: stacks-api
  #     STACKS_CORE_RPC_PORT: 3999
  #     STACKING_CYCLES: *STACKING_CYCLES
  #     STACKING_KEYS: 6a1a754ba863d7bab14adbbc3f8ebb090af9e871ace621d3e5ab634e1422885e01,b463f0df6c05d2f156393eee73f8016c5372caa0e9e29a901bb7171d90dc4f1401,7036b29cb5e235e5fd9b09ae3e8eec4404e44906814d5d01cbca968a60ed4bfb01
  #     STACKS_25_HEIGHT: *STACKS_25_HEIGHT
  #     STACKS_30_HEIGHT: *STACKS_30_HEIGHT
  #     POX_PREPARE_LENGTH: *POX_PREPARE_LENGTH
  #     POX_REWARD_LENGTH: *POX_REWARD_LENGTH
  #     EXIT_FROM_MONITOR: *EXIT_FROM_MONITOR
  #     SERVICE_NAME: monitor
  #   depends_on:
  #     - stacks-node
  #   entrypoint:
  #     - /bin/bash
  #     - -c
  #     - |
  #       set -e
  #       exec npx tsx /root/monitor.ts

  # stacks-signer-1:
  #   networks:
  #     - stacks
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.stacks-node
  #     args:
  #       GIT_COMMIT: *STACKS_BLOCKCHAIN_COMMIT
  #   depends_on:
  #     - stacks-node
  #   volumes:
  #     - ./signer-0.toml:/root/config.toml.in
  #     - chainstate:/chainstate
  #   environment:
  #     SIGNER_DB_PATH: /chainstate/stacks-signer-1.sqlite
  #     STACKS_NODE_HOST: stacks-node:20443
  #     STACKS_SIGNER_ENDPOINT: 0.0.0.0:30001
  #     SIGNER_PRIVATE_KEY: 6a1a754ba863d7bab14adbbc3f8ebb090af9e871ace621d3e5ab634e1422885e01
  #   entrypoint:
  #     - /bin/bash
  #     - -c
  #     - |
  #       set -e
  #       envsubst < config.toml.in > config.toml
  #       exec stacks-signer run --config config.toml

networks:
  stacks:
volumes:
  chainstate:
